version: '3'

services:
  mariadb:
    image: mariadb
    env_file: .env
    build:
      context: ./mariadb
      args:
        DB_DB: ${DB_DB}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  nginx:
    image: nginx
    build: ./nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_started

  wordpress:
    image: wordpress
    env_file: .env
    build: ./wordpress
    container_name: wordpress
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_started

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/jcambaki/data/mariadb
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /home/jcambaki/data/wordpress
      o: bind
