CREATE DATABASE DB_DB;
ALTER USER 'root'@localhost IDENTIFIED BY 'rootpass';

CREATE USER 'DB_USER'@'%' IDENTIFIED BY 'DB_PASS';
GRANT ALL PRIVILEGES ON wordpress.* TO 'DB_USER'@'%';

FLUSH PRIVILEGES;